* Fall 2021 - Lab 01

* Last name: Uddin

* First name: Ashfak

* GitHub username: ashfaku

* Notes: Lab 1 with 4 files:
	smaller.cpp, that takes 2 integer inputs and returns the smaller one,
	smaller3.cpp, that takes 3 integer inputs and returns the smallest one,
	leap.cpp, that takes a year input (like 2000) and says whether it's a leap year,
	and month.cpp, that takes in a year input and a month input, and says how many days that month has, including leap years.



* General instructions:
- Fill in your name and GitHub username on top. Do so by adding the
  info on the same line after a space after the colon not on the next line.  
- Use the Notes section to add any notes to the instructor.
- The main lab description can be found here:
  https://maryash.github.io/135/labs/lab_01.html 

* Daedalus specific instructions (changes from main spec):

We *will not* be using Gradescope for our labs. For this lab, for each
task (A through D) create the program files ~smaller.cpp~,
~smaller3.cpp~, ~leap.cpp~, and ~month.cpp~. Each should work as
specified in the main lab page. Add all four ~.cpp~ files to the
assignment repository, commit and push them. Do not add or push any
other files to to your repository.

Make sure to test each program to make sure it works correctly.

